apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - name: debug
    image: busybox  #lightweight linux tools
    command: ["sleep","3600"] # 1 hour samma alive hunxa
    stdin: true # input accept garna
    tty: true # Terminal attach garna
