apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "300m"
